add 'Iterators and generators' solution
danillampitskiy/Learning pull request #9
Opened 2023-10-04 14:27 UTC by danillampitskiy

2023-10-04 19:13 UTC, AnastasiiaGor requested changes

2023-10-04 19:13 UTC, AnastasiiaGor commented on Homeworks/Hw5/hw_ig.py
> +        if isinstance(elem, (list, tuple)):
doesn't work with other iterable objects (e.g dictionaries)
`hasattr(elem, "__iter__")` may help

2023-10-05 09:31 UTC, danillampitskiy commented on Homeworks/Hw5/hw_ig.py
> +        if isinstance(elem, (list, tuple)):
@AnastasiiaGor updated

2023-10-05 17:57 UTC, AnastasiiaGor approved these changes

2023-10-05 19:58 UTC, AnastasiiaGor approved these changes

2023-10-06 07:50 UTC, merged